bundle:
    name: LDAP Authentication bundle
    description: ldap-bundle enables to easily implement LDAP authentication on BackBee instances.
    author: Charles Rouillon <charles.rouillon@lp-digital.fr>
    version: 1.0
    enable: true
    thumbnail: /%bbapp.routing.resource_uri_prefix%/img/contents/picto-extnd-ldap.png
    config_per_site: true

ldap:
    search_dn: ""
    search_password: ""
    base_dn: ""
    filter: "(sAMAccountName={username})"
    persist_on_missing: false
    store_attributes: ['cn', 'description', 'name', 'mail', 'memberOf']