bundle:
    name: LDAP Authentication bundle
    description: ldap-bundle enables to easily implement LDAP authentication on BackBee instances.
    author: Charles Rouillon <charles.rouillon@lp-digital.fr>
    version: 0.2
    enable: true
    admin_controller:
        admin: LpDigital\Bundle\LdapBundle\Controller\AdminController
    admin_entry_point: admin.index
    thumbnail: /%bbapp.routing.resource_uri_prefix%/img/contents/picto-extnd-ldap.png
    config_per_site: true
    bundle_loader_recipes:
        template: [LpDigital\Bundle\LdapBundle\Ldap, loadViews]

ldap: []

parameters:
    persist_on_missing: false
    store_attributes: []
    default_backbee_groups: []